/* Generated by AN DISI Unibo */ 
package it.unibo.sendtemperaturecontroller;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sendtemperaturecontroller extends QActorMsgQueue{
	public MsgHandle_Sendtemperaturecontroller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
