/* Generated by AN DISI Unibo */ 
package it.unibo.ctxControlTemperature;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh5 extends AbstractEvh5 { 
	public Evh5(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
