/* Generated by AN DISI Unibo */ 
package it.unibo.roverobstacleavoiadanceagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Roverobstacleavoiadanceagent extends QActorMsgQueue{
	public MsgHandle_Roverobstacleavoiadanceagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
