/* Generated by AN DISI Unibo */ 
package it.unibo.ledonmbot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledonmbot extends QActorMsgQueue{
	public MsgHandle_Ledonmbot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
