/* Generated by AN DISI Unibo */ 
package it.unibo.ctxConsoleRobotGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh2 extends AbstractEvh2 { 
	public Evh2(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
