/* Generated by AN DISI Unibo */ 
package it.unibo.mbotcleanercontroller;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mbotcleanercontroller extends QActorMsgQueue{
	public MsgHandle_Mbotcleanercontroller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
