/* Generated by AN DISI Unibo */ 
package it.unibo.ctxControlTemperature;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxControlTemperature  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxcontroltemperature", "./srcMore/it/unibo/ctxControlTemperature/controlvalue.pl", 
		"./srcMore/it/unibo/ctxControlTemperature/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
