/* Generated by AN DISI Unibo */ 
package it.unibo.console;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractConsole extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractConsole(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/console/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/console/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("auth",auth);
	    	stateTab.put("consoleStart",consoleStart);
	    	stateTab.put("consolework",consolework);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "console tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Console Ready\"";
	    	println( temporaryStr );  
	    	//switchTo auth
	        switchToPlanAsNextState(pr, myselfName, "console_"+myselfName, 
	              "auth",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun auth = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_auth",0);
	     pr.incNumIter(); 	
	    	String myselfName = "auth";  
	    	//bbb
	     msgTransition( pr,myselfName,"console_"+myselfName,false,
	          new StateFun[]{stateTab.get("consoleStart") }, 
	          new String[]{"true","M","consolecmd" },
	          360000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_auth){  
	    	 println( getName() + " plan=auth WARNING:" + e_auth.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//auth
	    
	    StateFun consoleStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("consoleStart",-1);
	    	String myselfName = "consoleStart";  
	    	temporaryStr = "\"Console Start\"";
	    	println( temporaryStr );  
	    	printCurrentEvent(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consolecmd(start)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consolecmd") && 
	    		pengine.unify(curT, Term.createTerm("consolecmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"tempSensor(TEMP)","tempSensor(giveMeTemp)", guardVars ).toString();
	    		sendExtMsg("tempSensor","sendtemperaturecontrol", "ctxControlTemperature", QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consolecmd(halt)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consolecmd") && 
	    		pengine.unify(curT, Term.createTerm("consolecmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"usercmd(CMD,TEMP)","usercmd(halt,TEMP)", guardVars ).toString();
	    		sendExtMsg("usercmdMsg","mbotcleanercontroller", "ctxRobotCleaner", QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"console_"+myselfName,true,
	          new StateFun[]{stateTab.get("consolework") }, 
	          new String[]{"true","M","tempSensor" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_consoleStart){  
	    	 println( getName() + " plan=consoleStart WARNING:" + e_consoleStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//consoleStart
	    
	    StateFun consolework = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("consolework",-1);
	    	String myselfName = "consolework";  
	    	temporaryStr = "\"Console work\"";
	    	println( temporaryStr );  
	    	printCurrentEvent(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("tempSensor(TEMP)");
	    	if( currentMessage != null && currentMessage.msgId().equals("tempSensor") && 
	    		pengine.unify(curT, Term.createTerm("tempSensor(TEMP)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"usercmd(CMD,TEMP)","usercmd(start,TEMP)", guardVars ).toString();
	    		sendExtMsg("usercmdMsg","mbotcleanercontroller", "ctxRobotCleaner", QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"console_"+myselfName,false,true);
	    }catch(Exception e_consolework){  
	    	 println( getName() + " plan=consolework WARNING:" + e_consolework.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//consolework
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
