/* Generated by AN DISI Unibo */ 
package it.unibo.mbotcleaner;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractMbotcleaner extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractMbotcleaner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/mbotcleaner/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/mbotcleaner/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitStart",waitStart);
	    	stateTab.put("handleSensorData",handleSensorData);
	    	stateTab.put("doWork",doWork);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "mbotcleaner tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Robot Ready\"";
	    	println( temporaryStr );  
	    	//switchTo waitStart
	        switchToPlanAsNextState(pr, myselfName, "mbotcleaner_"+myselfName, 
	              "waitStart",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitStart",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitStart";  
	    	//bbb
	     msgTransition( pr,myselfName,"mbotcleaner_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSensorData"), stateTab.get("doWork") }, 
	          new String[]{"true","M","sensorMsg", "true","M","usercommand" },
	          36000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitStart){  
	    	 println( getName() + " plan=waitStart WARNING:" + e_waitStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitStart
	    
	    StateFun handleSensorData = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSensorData",-1);
	    	String myselfName = "handleSensorData";  
	    	printCurrentEvent(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sensorMsg(TEMP,TIME)");
	    	if( currentMessage != null && currentMessage.msgId().equals("sensorMsg") && 
	    		pengine.unify(curT, Term.createTerm("dataSensor(TEMP,TIME)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg  ="curTemperatureValue(X)";
	    		String parg1 ="curTemperatureValue(TEMP)";
	    		/* ReplaceRule */
	    		parg = updateVars(Term.createTerm("dataSensor(TEMP,TIME)"),  Term.createTerm("sensorMsg(TEMP,TIME)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		parg1 = updateVars(Term.createTerm("dataSensor(TEMP,TIME)"),  Term.createTerm("sensorMsg(TEMP,TIME)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg1);
	    		if( parg != null && parg1 != null  ) replaceRule(parg, parg1);	    		  					
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sensorMsg(TEMP,TIME)");
	    	if( currentMessage != null && currentMessage.msgId().equals("sensorMsg") && 
	    		pengine.unify(curT, Term.createTerm("dataSensor(TEMP,TIME)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg  ="curTime(X)";
	    		String parg1 ="curTime(TIME)";
	    		/* ReplaceRule */
	    		parg = updateVars(Term.createTerm("dataSensor(TEMP,TIME)"),  Term.createTerm("sensorMsg(TEMP,TIME)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		parg1 = updateVars(Term.createTerm("dataSensor(TEMP,TIME)"),  Term.createTerm("sensorMsg(TEMP,TIME)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg1);
	    		if( parg != null && parg1 != null  ) replaceRule(parg, parg1);	    		  					
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"mbotcleaner_"+myselfName,false,false);
	    }catch(Exception e_handleSensorData){  
	    	 println( getName() + " plan=handleSensorData WARNING:" + e_handleSensorData.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSensorData
	    
	    StateFun doWork = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doWork",-1);
	    	String myselfName = "doWork";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercommand(start)");
	    	if( currentMessage != null && currentMessage.msgId().equals("usercommand") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?evalSensor(start)" )) != null ){
	    		temporaryStr = "\"START\"";
	    		temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    		println( temporaryStr );  
	    		}
	    		else{ temporaryStr = "\"DON'T MOVE\"";
	    		temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    		println( temporaryStr );  
	    		}};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercommand(halt)");
	    	if( currentMessage != null && currentMessage.msgId().equals("usercommand") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"STOP\"";
	    		println( temporaryStr );  
	    		};//actionseq
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"mbotcleaner_"+myselfName,false,false);
	    }catch(Exception e_doWork){  
	    	 println( getName() + " plan=doWork WARNING:" + e_doWork.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doWork
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
