/* Generated by AN DISI Unibo */ 
package it.unibo.mbotcleaner;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mbotcleaner extends QActorMsgQueue{
	public MsgHandle_Mbotcleaner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
