/* Generated by AN DISI Unibo */ 
package it.unibo.realsonardetector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realsonardetector extends QActorMsgQueue{
	public MsgHandle_Realsonardetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
